### ISSUE TITLE
Mix of sync and async code in examples is misleading

### ISSUE THREAD

**Issue by jzaefferer** [benschwarz/cache.js#5]
The last example where you return from the $.get callback is misleading at best, considering the many people that don't get what async actually means, probably even harmful. As it has nothing to do with your actual library, could you update these examples and make them consistent, eg. use a callback also when fetching content from cache?

**Comment by benschwarz** [comment]
While I agree that the readme could be stronger, fuller, better; I feel that the callback displays not only why you'd use `cache.js`, but how one would use it also. 

A real usage example that displays the API... Having said that, I'd be interested to see what you'd do yourself. So if you're happy to fork and provide a documentation commit, I'll be happy to review.

**Comment by jzaefferer** [comment]
I'm just looking for an example where you start with a user-provided callback, and either call that with the cached data, or pass it on to the $.get method. That way it'll be clear that you can't just mix ajax calls with synchronous cache requests if your code needs to handle async code.
